#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

# branches to build
branches:
  # whitelist
  only:
    - master
    - v1.0

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Skipping commits with particular message or from specific user
#skip_commits:
#  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message
#  author: John                                      # Commit author's username, name, email or regexp maching one of these.

# Including commits with particular message or from specific user
#only_commits:
#  message: /build/                # Start a new build if message contains 'build'
#  author: jack@company.com        # Start a new build for commit of user with email jack@company.com

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
#skip_commits:
#  files:
#    - docs/*
#    - '**/*.html'

# Including commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
#only_commits:
#  files:
#    - Project-A/
#    - Project-B/

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2017

environment:
  # 0-4 warning levels; 0 is no warnings
  MSBUILD_FLAGS: /maxcpucount
  BOOST_ROOT: C:/Libraries/boost_1_65_1
  matrix:
    - generator: "Visual Studio 14 2015 Win64"
    - generator: "Visual Studio 15 2017 Win64"

install:
  - ps: cd C:\Tools\vcpkg
  - ps: vcpkg --triplet x64-windows install freeimage glbinding glfw3 glm opencl freetype

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - cmake --version

# clone directory
clone_folder: c:\projects\forge

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  #  allow_failures:
  #    - platform: x86
  #      configuration: Debug
  #    - platform: x64
  #      configuration: Release

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - RelWithDebInfo
  # - Debug
  # - Release

cache:
  - C:\Tools\vcpkg\installed\ -> appveyor.yml

build:
  parallel: true                                    # enable MSBuild parallel builds
  project: c:/projects/forge/build/Forge.sln        # path to Visual Studio solution or project

  # MSBuild verbosity level
  # verbosity: quiet|minimal|normal|detailed
  verbosity: quiet

# scripts to run before build
before_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake %APPVEYOR_BUILD_FOLDER% -G "%generator%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/build/package -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DFreeImage_ROOT="c:/tools/vcpkg/installed/x64-windows"
  - cmake --build . --target ALL_BUILD --config %configuration% -- /nologo
  - cmake --build . --target INSTALL --config %configuration% -- /nologo
